### ISSUE TITLE
Criação de marca

### ISSUE THREAD

**Issue by tbzambe** [Queline-project/documentacao#1]
@Queline-project/design precisamos de uma marca pro Queline, lembrando que não é a marca do produto a ser desenvolvido, a idéia é começar a montar a identidade do grupo como um todo.

**Comment by co-ana** [comment]
![qline](https://cloud.githubusercontent.com/assets/17653421/13940208/2db0d178-efba-11e5-8435-de8d98de8b93.png)

**Comment by tbzambe** [comment]
Show!
