### ISSUE TITLE
Documentação da Aplicação Web de Monitores 

### ISSUE THREAD

**Issue by ramonpenna19** [Queline-project/documentacao#3]
A aplicação, resumidamente, fará o agendamento de uma aula com um monitor da UVV.
O aluno deverá realizar o login na aplicação, e buscar um Monitor através de um filtro por curso e matéria. Ao escolher um Monitor (aluno da UVV com status de monitor) e verificar a disponibilidade do mesmo em algum dia/hora específico. Selecionando a data da aula, o aluno envia uma solicitação para o Monitor, que deverá respondê-la positiva ou negativamente. A resposta do Monitor será enviada para o aluno solicitante através de notificação na aplicação e por email.

APLICAÇÃO RESPONSIVA

(Aluno - Curso - Matéria - Agenda)

Opcionais/Adicionais:
Foto (acho desnecessário, já que não será uma rede social e todos serão alunos)
Comentário/Rating público no perfil do Monitor, sobre qualidade da aula, etc.
Criar um calendário/agenda visual
Permitir a criação de grupos de estudo dentro de Matéria/Curso

**Comment by tbzambe** [comment]
Estou de acordo com tudo, inclusive os opcionais. Só sugiro que pelo menos o monitor tenha cadastro com foto, já que é possível que um aluno chegue lá e não saiba com quem tirar as dúvidas. Outra coisa que poderia facilitar um pouco é a inserção dos horários que o usuário tem indisponíveis logo no cadastro. Por exemplo:
- Aulas:

```
19:10 até as 22:45 de Segunda a Quinta
```
- Outros:

```
12:30 até as 18:30 de Segunda a Sexta
```
- O aplicativo identifica o intervalo de disponibilidade:

```
07:10 até as 11:30 de Segunda a Sexta
19:30 até as 22:45 Sexta
```

Mas isso só seria legal se buscasse do banco quais matérias cursadas e horários do aluno sem precisar cadastrar essa parte manualmente. Caso seu horário disponível coincida com o que o monitor inseriu, o aplicativo sugere um dia e hora bons para ambos. Caso contrário, daí o aluno deve se adequar ao horário estipulado pelo monitor.

**Comment by tbzambe** [comment]
@Queline-project/lideres meio que precisamos finalizar isso aqui.
- [x] Estabelecer funcionalidades
- [x] Levantar requisitos
- [x] Esboçar backlog
